name: timesheet_frontend
description: A Flutter web frontend for the Timesheet app
environment:
  sdk: '>=2.18.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  web: ^1.1.1  # or latest version
#  websocket: ^0.0.1
  web_socket_channel: ^3.0.3
  provider: ^6.0.5
  intl: ^0.20.2
  pdf: ^3.10.1
dev_dependencies:
  flutter_test:
    sdk: flutter
