name: timesheet_server
environment:
  sdk: '>=2.18.0 <4.0.0'
dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_static: ^1.1.0
  shelf_web_socket: ^3.0.0
  sqlite3: ^2.9.3
  path: ^1.8.0
  json_annotation: ^4.8.0
  crypto: ^3.0.2
  bcrypt: ^1.0.0
#  jwt: ^0.0.0
  dart_jsonwebtoken: ^3.3.1
  logging: ^1.0.2
dev_dependencies:
  build_runner: ^2.4.0
  json_serializable: ^6.6.0
