name: timesheet_server
environment:
  sdk: '>=2.18.0 <4.0.0'
dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_static: ^1.1.0
  shelf_web_socket: ^1.0.1
  sqlite3: ^1.5.0
  path: ^1.8.0
  json_annotation: ^4.8.0
  crypto: ^3.0.2
  bcrypt: ^4.0.0
  jwt: ^0.5.0
  logging: ^1.0.2
dev_dependencies:
  build_runner: ^2.4.0
  json_serializable: ^6.6.0
