name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
      - name: Install dependencies (server)
        run: |
          cd server
          dart pub get
      - name: Dart analyze (server)
        run: |
          cd server
          dart analyze
      - name: Install frontend deps
        run: |
          cd frontend
          flutter pub get
      - name: Run flutter tests
        run: |
          cd frontend
          flutter test --no-pub
      - name: Build web
        run: |
          cd frontend
          flutter build web
